language: python

python:
  - "2.6"

env:
  - TOXENV=py25,py25-1.4
  - TOXENV=py26,py26-1.4
  - TOXENV=py27,py27-1.4
  - TOXENV=docs

# command to install dependencies
install:
    - sudo aptitude install -y binutils gdal-bin libproj-dev postgresql-9.1-postgis postgresql-server-dev-9.1
    - sudo tests/create_template_postgis-debian.sh
    - createdb -T template_postgis tastypie.db -U postgres
    - pip install tox

# command to run tests
script:
    - tox
